#!/usr/bin/env python3
"""
SHAP Analysis for TabPFN Regression Model (with Local Dataset Support)
=======================================================================

This script performs SHAP (SHapley Additive exPlanations) analysis on a TabPFN
regression model. It supports loading data from sklearn or local CSV file.

Usage:
    # Load from sklearn (default)
    python shap_analysis_v2.py
    
    # Load from local CSV
    python shap_analysis_v2.py --use-local
    
    # Save dataset first, then analyze
    python data_loader.py --save
    python shap_analysis_v2.py --use-local

Requirements:
    - tabpfn
    - shap
    - matplotlib
    - numpy
    - pandas
    - scikit-learn

Author: Generated by Claude Code
Date: 2026-03-20
"""

from __future__ import annotations

import argparse
import warnings
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
from sklearn.metrics import mean_squared_error, r2_score

from tabpfn import TabPFNRegressor
from tabpfn.constants import ModelVersion

# Import our data loader
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'dataset'))
from data_loader import load_from_csv, load_from_sklearn, save_dataset

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore')

# Configure matplotlib
matplotlib.use('Agg')
plt.style.use('default')


def train_and_evaluate(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
    n_estimators: int = 1
) -> TabPFNRegressor:
    """Train model and show performance metrics."""
    print("\n" + "=" * 70)
    print("Training TabPFN v2 Regressor")
    print("=" * 70)
    print(f"Parameters:")
    print(f"  - Model version: v2")
    print(f"  - n_estimators: {n_estimators}")
    
    model = TabPFNRegressor.create_default_for_version(
        ModelVersion.V2,
        n_estimators=n_estimators
    )
    model.fit(X_train, y_train)
    
    # Evaluate
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    print(f"\n✓ Training completed")
    print(f"  - Test MSE: {mse:.2f}")
    print(f"  - Test R²: {r2:.4f}")
    
    return model


def compute_shap_values(
    model: TabPFNRegressor,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    n_background: int = 50,
    n_test_samples: int = 50
) -> tuple:
    """Compute SHAP values using KernelExplainer."""
    print("\n" + "=" * 70)
    print("Computing SHAP Values")
    print("=" * 70)
    print(f"Using KernelExplainer")
    print(f"  - Background samples: {n_background}")
    print(f"  - Test samples: {n_test_samples}")
    print(f"Note: This may take a few minutes...")
    
    background = X_train.iloc[:n_background]
    X_test_sample = X_test.iloc[:n_test_samples]
    
    explainer = shap.KernelExplainer(model.predict, background)
    shap_values = explainer.shap_values(X_test_sample)
    
    print(f"✓ SHAP values computed")
    print(f"  - Shape: {shap_values.shape}")
    print(f"  - Expected value: {explainer.expected_value:.2f}")
    
    return shap_values, explainer, X_test_sample


def analyze_and_visualize(
    shap_values: np.ndarray,
    X_test_sample: pd.DataFrame,
    feature_names: list,
    output_dir: Path = Path('.')
) -> None:
    """Analyze feature importance and generate visualizations."""
    print("\n" + "=" * 70)
    print("Feature Importance Analysis")
    print("=" * 70)
    
    # Calculate importance
    mean_abs_shap = np.abs(shap_values).mean(axis=0)
    feature_importance = pd.DataFrame({
        'feature': feature_names,
        'mean_abs_shap': mean_abs_shap
    }).sort_values('mean_abs_shap', ascending=False)
    
    print("\nRanked by |SHAP| value:")
    print("-" * 50)
    max_val = feature_importance['mean_abs_shap'].max()
    for _, row in feature_importance.iterrows():
        bar = '█' * int(row['mean_abs_shap'] / max_val * 30)
        print(f"{row['feature']:>10} | {bar:<30} | {row['mean_abs_shap']:>6.2f}")
    
    # Generate plots
    print("\n" + "=" * 70)
    print("Generating Visualizations")
    print("=" * 70)
    
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Bar plot
    print("\n1. Feature importance bar plot...")
    fig, ax = plt.subplots(figsize=(10, 6))
    shap.summary_plot(shap_values, X_test_sample, plot_type="bar", show=False)
    plt.title('TabPFN - Feature Importance (SHAP)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    path = output_dir / 'shap_feature_importance_bar.png'
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"   ✓ {path}")
    
    # 2. Beeswarm plot
    print("\n2. Beeswarm plot...")
    fig, ax = plt.subplots(figsize=(10, 8))
    shap.summary_plot(shap_values, X_test_sample, show=False)
    plt.title('TabPFN - Feature Impact Distribution', fontsize=14, fontweight='bold')
    plt.tight_layout()
    path = output_dir / 'shap_beeswarm.png'
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"   ✓ {path}")
    
    # 3. Dependence plots
    print("\n3. Dependence plots for top 2 features...")
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    top_2 = feature_importance.head(2)['feature'].tolist()
    
    plt.sca(axes[0])
    shap.dependence_plot(top_2[0], shap_values, X_test_sample, show=False, ax=axes[0])
    axes[0].set_title(f'{top_2[0].upper()} Impact', fontsize=12, fontweight='bold')
    
    plt.sca(axes[1])
    shap.dependence_plot(top_2[1], shap_values, X_test_sample, show=False, ax=axes[1])
    axes[1].set_title(f'{top_2[1].upper()} Impact', fontsize=12, fontweight='bold')
    
    plt.tight_layout()
    path = output_dir / 'shap_dependence_top2.png'
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"   ✓ {path}")


def main():
    parser = argparse.ArgumentParser(description='SHAP Analysis for TabPFN')
    parser.add_argument('--use-local', action='store_true',
                        help='Load dataset from local CSV file')
    parser.add_argument('--save-data', action='store_true',
                        help='Save sklearn dataset to CSV before analysis')
    parser.add_argument('--n-estimators', type=int, default=1,
                        help='Number of ensemble estimators (default: 1)')
    parser.add_argument('--output-dir', default='.',
                        help='Directory to save output plots')
    args = parser.parse_args()
    
    print("\n" + "🚀 " * 20)
    print("SHAP Analysis for TabPFN")
    print("🚀 " * 20 + "\n")
    
    # Save dataset if requested
    if args.save_data:
        save_dataset('diabetes_dataset.csv')
        print()
    
    # Load data
    if args.use_local:
        try:
            X_train, X_test, y_train, y_test, feature_names = load_from_csv(
                'diabetes_dataset.csv'
            )
        except FileNotFoundError:
            print("Local dataset not found. Creating it first...")
            save_dataset('diabetes_dataset.csv')
            X_train, X_test, y_train, y_test, feature_names = load_from_csv(
                'diabetes_dataset.csv'
            )
    else:
        X_train, X_test, y_train, y_test, feature_names = load_from_sklearn()
    
    # Train model
    model = train_and_evaluate(
        X_train, X_test, y_train, y_test,
        n_estimators=args.n_estimators
    )
    
    # Compute SHAP values
    shap_values, explainer, X_test_sample = compute_shap_values(
        model, X_train, X_test
    )
    
    # Analyze and visualize
    analyze_and_visualize(
        shap_values, X_test_sample, feature_names,
        output_dir=Path(args.output_dir)
    )
    
    print("\n" + "=" * 70)
    print("✅ Analysis Complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
